version: 2.1

orbs:
  terraform: circleci/terraform@3.1 
  aws-cli: circleci/aws-cli@4.1.3


executors:
  terraform-executor:
    machine:
      image: ubuntu-2204:current
      resource_class: medium  

jobs:
  validate-terraform-install:
    executor: terraform-executor 
    parameters:
      environment:
        type: string
        default: "dev"
    steps:
      - checkout
      - terraform/install:
          arch: amd64 
          os: linux 
          terraform_version: '1.9.7'
      - run:
          command: ls -lah
        
      - run:
          name: checking dependencies
          command: |
            node -v 
            docker -v
            terraform -v
      # - run:
      #     name: Set environment Variable
      #     command: |
      #       if [[ "<< parameters.environment >>" != "dev" && 
      #             "<< parameters.environment >>" != "prod" && 
      #             "<< parameters.environment >>" != "pre-prod" && 
      #             "<< parameters.environment >>" != "stage" ]]; then
      #         export environment="dev"
      #       else
      #         export environment="<< parameters.environment >>"
      #       fi
      - aws-cli/install
      - aws-cli/setup
          # access-key-id: $AWS_ACCESS_KEY_ID
          # region: us-east-1 
          # profile_name: default
          # secret-access-key: $AWS_SECRET_ACCESS_KEY
      - terraform/init
      - run:
          name: Select Workspace
          command: |
            terraform workspace select << parameters.environment >>
      - terraform/plan
      - terraform/apply
      - terraform/destroy
    

      

workflows:
  deploy:
    jobs:
      - validate-terraform-install  
